#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define PIECE_SIZE 150
#define PADDING 5

#define MOVE_FACTOR 1.f/60

#define TOP_LEFT_X (WINDOW_WIDTH/2.f) - (3*PIECE_SIZE + 2*PADDING) / 2.f
#define TOP_LEFT_Y (WINDOW_HEIGHT/2.f) - (3*PIECE_SIZE + 2*PADDING) / 2.f

#define TOP_RIGHT_X (WINDOW_WIDTH/2.f) + (3*PIECE_SIZE + 2*PADDING) / 2.f
#define TOP_RIGHT_Y (WINDOW_HEIGHT/2.f) - (3*PIECE_SIZE + 2*PADDING) / 2.f
#endif
