#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define PIECE_SIZE 150
#define PADDING 5

#define MOVE_FACTOR 1.f/30

#define CUBE_LEFT_X (WINDOW_WIDTH/2.f) - (3*PIECE_SIZE + 2*PADDING) / 2.f
#define CUBE_RIGHT_X (WINDOW_WIDTH/2.f) + (3*PIECE_SIZE + 2*PADDING) / 2.f
#define CUBE_TOP_Y (WINDOW_HEIGHT/2.f) - (3*PIECE_SIZE + 2*PADDING) / 2.f
#define CUBE_BOTTOM_Y (WINDOW_HEIGHT/2.f) + (3*PIECE_SIZE + 2*PADDING) / 2.f

#define MAX_SCORE 100000
#define TIME_PENALTY 160
#define SWAP_PENALTY 100
#define MOVE_PENALTY 40

#endif
