#ifndef STATE_H
#define STATE_H

enum GameState
{
	START,
	GAME_START,

	IDLE_UNSOLVED,
	IDLE_UNSOLVED_PAUSED,

	MOVING_RIGHT_1_UNSOLVED,
	MOVING_RIGHT_1_UNSOLVED_PAUSED,

	MOVING_RIGHT_2_UNSOLVED,
	MOVING_RIGHT_2_UNSOLVED_PAUSED,

	MOVING_LEFT_1_UNSOLVED,
	MOVING_LEFT_1_UNSOLVED_PAUSED,

	MOVING_LEFT_2_UNSOLVED,
	MOVING_LEFT_2_UNSOLVED_PAUSED,

	IDLE_SOLVED,
	IDLE_SOLVED_PAUSED,

	MOVING_RIGHT_1_SOLVED,
	MOVING_RIGHT_1_SOLVED_PAUSED,

	MOVING_RIGHT_2_SOLVED,
	MOVING_RIGHT_2_SOLVED_PAUSED,

	MOVING_LEFT_1_SOLVED,
	MOVING_LEFT_1_SOLVED_PAUSED,

	MOVING_LEFT_2_SOLVED,
	MOVING_LEFT_2_SOLVED_PAUSED,

	WIN,
	EXIT
};

class StateManager
{
	GameState gameState;
public:
	GameState getState(){return gameState;}
	void switchToState(GameState newState);
};

#endif
